
name: Clone Releases

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/clone-releases
        with:
          src_repo: cobrowseio/cobrowse-enterprise-helm
